package com.dmjm.model;
// Generated 13-abr-2025 18:47:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Impu01 generated by hbm2java
 */
public class Impu01  implements java.io.Serializable {


     private int cveEsqimpu;
     private String descripesq;
     private Double impuesto1;
     private Integer imp1aplica;
     private Double impuesto2;
     private Integer imp2aplica;
     private Double impuesto3;
     private Integer imp3aplica;
     private Double impuesto4;
     private Integer imp4aplica;
     private String status;
     private String uuid;
     private Date versionSinc;
     private Integer imp6aplica;
     private Integer imp8aplica;
     private Double impuesto8;
     private Integer imp7aplica;
     private Double impuesto7;
     private Double impuesto6;
     private Integer imp5aplica;
     private Double impuesto5;

    public Impu01() {
    }


    public Impu01(int cveEsqimpu) {
        this.cveEsqimpu = cveEsqimpu;
    }
    public Impu01(int cveEsqimpu, String descripesq, Double impuesto1, Integer imp1aplica, Double impuesto2, Integer imp2aplica, Double impuesto3, Integer imp3aplica, Double impuesto4, Integer imp4aplica, String status, String uuid, Date versionSinc, Integer imp6aplica, Integer imp8aplica, Double impuesto8, Integer imp7aplica, Double impuesto7, Double impuesto6, Integer imp5aplica, Double impuesto5) {
       this.cveEsqimpu = cveEsqimpu;
       this.descripesq = descripesq;
       this.impuesto1 = impuesto1;
       this.imp1aplica = imp1aplica;
       this.impuesto2 = impuesto2;
       this.imp2aplica = imp2aplica;
       this.impuesto3 = impuesto3;
       this.imp3aplica = imp3aplica;
       this.impuesto4 = impuesto4;
       this.imp4aplica = imp4aplica;
       this.status = status;
       this.uuid = uuid;
       this.versionSinc = versionSinc;
       this.imp6aplica = imp6aplica;
       this.imp8aplica = imp8aplica;
       this.impuesto8 = impuesto8;
       this.imp7aplica = imp7aplica;
       this.impuesto7 = impuesto7;
       this.impuesto6 = impuesto6;
       this.imp5aplica = imp5aplica;
       this.impuesto5 = impuesto5;
    }

    public int getCveEsqimpu() {
        return this.cveEsqimpu;
    }

    public void setCveEsqimpu(int cveEsqimpu) {
        this.cveEsqimpu = cveEsqimpu;
    }
    public String getDescripesq() {
        return this.descripesq;
    }

    public void setDescripesq(String descripesq) {
        this.descripesq = descripesq;
    }
    public Double getImpuesto1() {
        return this.impuesto1;
    }

    public void setImpuesto1(Double impuesto1) {
        this.impuesto1 = impuesto1;
    }
    public Integer getImp1aplica() {
        return this.imp1aplica;
    }

    public void setImp1aplica(Integer imp1aplica) {
        this.imp1aplica = imp1aplica;
    }
    public Double getImpuesto2() {
        return this.impuesto2;
    }

    public void setImpuesto2(Double impuesto2) {
        this.impuesto2 = impuesto2;
    }
    public Integer getImp2aplica() {
        return this.imp2aplica;
    }

    public void setImp2aplica(Integer imp2aplica) {
        this.imp2aplica = imp2aplica;
    }
    public Double getImpuesto3() {
        return this.impuesto3;
    }

    public void setImpuesto3(Double impuesto3) {
        this.impuesto3 = impuesto3;
    }
    public Integer getImp3aplica() {
        return this.imp3aplica;
    }

    public void setImp3aplica(Integer imp3aplica) {
        this.imp3aplica = imp3aplica;
    }
    public Double getImpuesto4() {
        return this.impuesto4;
    }

    public void setImpuesto4(Double impuesto4) {
        this.impuesto4 = impuesto4;
    }
    public Integer getImp4aplica() {
        return this.imp4aplica;
    }

    public void setImp4aplica(Integer imp4aplica) {
        this.imp4aplica = imp4aplica;
    }
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Date getVersionSinc() {
        return this.versionSinc;
    }

    public void setVersionSinc(Date versionSinc) {
        this.versionSinc = versionSinc;
    }
    public Integer getImp6aplica() {
        return this.imp6aplica;
    }

    public void setImp6aplica(Integer imp6aplica) {
        this.imp6aplica = imp6aplica;
    }
    public Integer getImp8aplica() {
        return this.imp8aplica;
    }

    public void setImp8aplica(Integer imp8aplica) {
        this.imp8aplica = imp8aplica;
    }
    public Double getImpuesto8() {
        return this.impuesto8;
    }

    public void setImpuesto8(Double impuesto8) {
        this.impuesto8 = impuesto8;
    }
    public Integer getImp7aplica() {
        return this.imp7aplica;
    }

    public void setImp7aplica(Integer imp7aplica) {
        this.imp7aplica = imp7aplica;
    }
    public Double getImpuesto7() {
        return this.impuesto7;
    }

    public void setImpuesto7(Double impuesto7) {
        this.impuesto7 = impuesto7;
    }
    public Double getImpuesto6() {
        return this.impuesto6;
    }

    public void setImpuesto6(Double impuesto6) {
        this.impuesto6 = impuesto6;
    }
    public Integer getImp5aplica() {
        return this.imp5aplica;
    }

    public void setImp5aplica(Integer imp5aplica) {
        this.imp5aplica = imp5aplica;
    }
    public Double getImpuesto5() {
        return this.impuesto5;
    }

    public void setImpuesto5(Double impuesto5) {
        this.impuesto5 = impuesto5;
    }




}


