package com.dmjm.model;
// Generated 03-mar-2025 21:34:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idusuario;
     private Perfiles perfiles;
     private String clave;
     private String nombre;
     private String rfc;
     private String calle;
     private String numext;
     private String colonia;
     private String codigo;
     private String localidad;
     private String municipio;
     private String estado;
     private String telefono;
     private String clasific;
     private Integer listaPrec;
     private String cveVend;
     private String password;
     private String correo;
     private Date fecha;
     private boolean estatus;

    public Usuarios() {
    }


    public Usuarios(int idusuario, Perfiles perfiles, String clave, String password, String correo, Date fecha, boolean estatus) {
        this.idusuario = idusuario;
        this.perfiles = perfiles;
        this.clave = clave;
        this.password = password;
        this.correo = correo;
        this.fecha = fecha;
        this.estatus = estatus;
    }
    public Usuarios(int idusuario, Perfiles perfiles, String clave, String nombre, String rfc, String calle, String numext, String colonia, String codigo, String localidad, String municipio, String estado, String telefono, String clasific, Integer listaPrec, String cveVend, String password, String correo, Date fecha, boolean estatus) {
       this.idusuario = idusuario;
       this.perfiles = perfiles;
       this.clave = clave;
       this.nombre = nombre;
       this.rfc = rfc;
       this.calle = calle;
       this.numext = numext;
       this.colonia = colonia;
       this.codigo = codigo;
       this.localidad = localidad;
       this.municipio = municipio;
       this.estado = estado;
       this.telefono = telefono;
       this.clasific = clasific;
       this.listaPrec = listaPrec;
       this.cveVend = cveVend;
       this.password = password;
       this.correo = correo;
       this.fecha = fecha;
       this.estatus = estatus;
    }

    public int getIdusuario() {
        return this.idusuario;
    }

    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }

    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRfc() {
        return this.rfc;
    }

    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getCalle() {
        return this.calle;
    }

    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumext() {
        return this.numext;
    }

    public void setNumext(String numext) {
        this.numext = numext;
    }
    public String getColonia() {
        return this.colonia;
    }

    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getClasific() {
        return this.clasific;
    }

    public void setClasific(String clasific) {
        this.clasific = clasific;
    }
    public Integer getListaPrec() {
        return this.listaPrec;
    }

    public void setListaPrec(Integer listaPrec) {
        this.listaPrec = listaPrec;
    }
    public String getCveVend() {
        return this.cveVend;
    }

    public void setCveVend(String cveVend) {
        this.cveVend = cveVend;
    }
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstatus() {
        return this.estatus;
    }

    public void setEstatus(boolean estatus) {
        this.estatus = estatus;
    }




}


